package internal

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const marker = "# Generated by cpm (Claude Profile Manager)"

func InstallWrapper(scriptPath, content string) error {
	dir := filepath.Dir(scriptPath)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	existing, err := os.ReadFile(scriptPath)
	if err == nil && string(existing) == content {
		return nil
	}

	if err := os.WriteFile(scriptPath, []byte(content), 0o755); err != nil {
		return err
	}
	fmt.Printf("  installed %s\n", scriptPath)
	return nil
}

func CleanupStaleScripts(binDir string, activeNames map[string]bool) {
	entries, err := os.ReadDir(binDir)
	if err != nil {
		return
	}

	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		if activeNames[entry.Name()] {
			continue
		}
		path := filepath.Join(binDir, entry.Name())
		content, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		if strings.Contains(string(content), marker) {
			os.Remove(path)
			fmt.Printf("  removed stale script %s\n", path)
		}
	}
}
